#define AppName "AUCC Agent"
#ifndef AppVersion
#define AppVersion "1.0.0"
#endif
#ifndef AgentServerURL
#define AgentServerURL ""
#endif

[Setup]
AppId={{8DC60F6B-F9F0-48A6-BF01-D0831DDA5F85}
AppName={#AppName}
AppVersion={#AppVersion}
DefaultDirName={userpf}\AUCC Agent
DefaultGroupName=AUCC Agent
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
MinVersion=10.0
WizardStyle=modern
OutputDir=dist
OutputBaseFilename=AUCCAgentSetup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
CloseApplications=yes
RestartApplications=no
UninstallDisplayIcon={app}\AUCCAgent.exe

[Files]
Source: "dist\AUCCAgent.exe"; DestDir: "{app}"; Flags: ignoreversion; AfterInstall: WriteStationConfig
Source: "dist\AUCCUpdater.exe"; DestDir: "{app}"; Flags: ignoreversion
#ifdef DeploymentPackage
#ifdef EmbeddedDeployment
Source: "server-ca.pem"; DestDir: "{app}"; Flags: ignoreversion
Source: "deployment.ini"; Flags: dontcopy
#else
Source: "{src}\server-ca.pem"; DestDir: "{app}"; Flags: external ignoreversion
#endif
#else
#ifexist "dist\server-ca.pem"
Source: "dist\server-ca.pem"; DestDir: "{app}"; Flags: ignoreversion
#endif
#endif

[Icons]
Name: "{group}\AUCC Agent"; Filename: "{app}\AUCCAgent.exe"; WorkingDir: "{app}"

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "AUCC Agent"; ValueData: """{app}\AUCCAgent.exe"""; Flags: uninsdeletevalue

[Run]
Filename: "{app}\AUCCAgent.exe"; Parameters: "--enroll"; WorkingDir: "{app}"; Flags: runhidden
Filename: "{app}\AUCCAgent.exe"; Description: "Start AUCC Agent now (locks this Windows session)"; WorkingDir: "{app}"; Flags: postinstall nowait skipifsilent

[UninstallDelete]
Type: files; Name: "{localappdata}\AUCC Agent\config.json"
Type: dirifempty; Name: "{localappdata}\AUCC Agent"

[Code]
var
  SettingsPage: TInputQueryWizardPage;
  EnrollmentToken: String;
  DeploymentIniFile: String;

#ifdef DeploymentPackage
function InitializeSetup: Boolean;
var
  URL: String;
  CAFile: String;
begin
#ifdef EmbeddedDeployment
  ExtractTemporaryFile('deployment.ini');
  ExtractTemporaryFile('server-ca.pem');
  DeploymentIniFile := ExpandConstant('{tmp}\deployment.ini');
  CAFile := ExpandConstant('{tmp}\server-ca.pem');
#else
  DeploymentIniFile := ExpandConstant('{src}\deployment.ini');
  CAFile := ExpandConstant('{src}\server-ca.pem');
#endif
  URL := GetIniString('AUCC', 'ServerURL', '', DeploymentIniFile);
  EnrollmentToken := GetIniString('AUCC', 'EnrollmentToken', '', DeploymentIniFile);
  Result := (Pos('wss://', LowerCase(URL)) = 1) and
    (Copy(URL, Length(URL) - 12, 13) = '/api/ws/agent') and
    (Length(EnrollmentToken) >= 32) and (Length(EnrollmentToken) <= 256) and
    FileExists(CAFile);
  if not Result then
    MsgBox('This private client package is incomplete. Copy the complete package generated by AUCC Server.', mbError, MB_OK);
end;
#endif

function ConfigFilePath: String;
begin
  Result := ExpandConstant('{localappdata}\AUCC Agent\config.json');
end;

procedure InitializeWizard;
begin
  SettingsPage := CreateInputQueryPage(wpSelectDir, 'Station settings',
    'Connect this computer to AUCC',
    'The agent will use this Windows computer name and request approval in Admin automatically. For a remote server, use a trusted wss:// URL.');
  SettingsPage.Add('Server URL:', False);
#ifdef DeploymentPackage
  SettingsPage.Values[0] := GetIniString('AUCC', 'ServerURL', '', DeploymentIniFile);
#else
  if not FileExists(ConfigFilePath) then
  begin
    SettingsPage.Values[0] := '{#AgentServerURL}';
    if SettingsPage.Values[0] = '' then
      SettingsPage.Values[0] := 'ws://localhost:8000/api/ws/agent';
  end;
#endif
end;

function ServerURLValid(ServerURL: String): Boolean;
var
  LowerURL: String;
begin
  LowerURL := LowerCase(Trim(ServerURL));
  Result := (Length(LowerURL) >= 13) and
            ((Pos('wss://', LowerURL) = 1) or
             (Pos('ws://localhost:', LowerURL) = 1) or
             (Pos('ws://127.0.0.1:', LowerURL) = 1) or
             (Pos('ws://[::1]:', LowerURL) = 1)) and
            (Copy(LowerURL, Length(LowerURL) - 12, 13) = '/api/ws/agent');
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
#ifdef DeploymentPackage
  Result := PageID = SettingsPage.ID;
#else
  Result := (PageID = SettingsPage.ID) and
    (FileExists(ConfigFilePath) or
     (('{#AgentServerURL}' <> '') and ServerURLValid(SettingsPage.Values[0])));
#endif
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ServerURL: String;
begin
  Result := True;
  if CurPageID <> SettingsPage.ID then Exit;

  ServerURL := Trim(SettingsPage.Values[0]);

  if not ServerURLValid(ServerURL) then
  begin
    MsgBox('Enter the server URL ending in /api/ws/agent. Use wss:// for a remote server.', mbError, MB_OK);
    Result := False;
  end;
end;

function JsonEscape(const Value: String): String;
var
  I: Integer;
  C: String;
begin
  Result := '';
  for I := 1 to Length(Value) do
  begin
    C := Copy(Value, I, 1);
    if C = '\' then Result := Result + '\\'
    else if C = '"' then Result := Result + '\"'
    else if C = #10 then Result := Result + '\n'
    else if C = #13 then Result := Result + '\r'
    else if C = #9 then Result := Result + '\t'
    else if Ord(Value[I]) < 32 then RaiseException('Invalid control character in station settings')
    else Result := Result + C;
  end;
end;

procedure WriteStationConfig;
var
  ConfigDir: String;
  CAFile: String;
  Lines: TArrayOfString;
begin
  if FileExists(ConfigFilePath) then Exit;

  ConfigDir := ExpandConstant('{localappdata}\AUCC Agent');
  if not ForceDirectories(ConfigDir) then
    RaiseException('Could not create the private station settings folder');

#ifdef DeploymentPackage
  CAFile := ExpandConstant('{app}\server-ca.pem');
#else
#ifexist "dist\server-ca.pem"
  CAFile := ExpandConstant('{app}\server-ca.pem');
#else
  CAFile := '';
#endif
#endif
  SetArrayLength(Lines, 7);
  Lines[0] := '{';
  Lines[1] := '  "server_url": "' + JsonEscape(Trim(SettingsPage.Values[0])) + '",';
  Lines[2] := '  "server_ca_file": "' + JsonEscape(CAFile) + '",';
  Lines[3] := '  "ping_interval_seconds": 15,';
  Lines[4] := '  "auto_enroll": true,';
  Lines[5] := '  "enrollment_token": "' + JsonEscape(EnrollmentToken) + '"';
  Lines[6] := '}';
  if not SaveStringsToUTF8FileWithoutBOM(ConfigFilePath, Lines, False) then
    RaiseException('Could not save the private station settings');
end;

#ifdef DeploymentPackage
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Existing: AnsiString;
begin
  Result := '';
  if FileExists(ConfigFilePath) then
  begin
    if not LoadStringFromFile(ConfigFilePath, Existing) or
      (Pos('"server_url": "' + JsonEscape(SettingsPage.Values[0]) + '"', String(Existing)) = 0) then
      Result := 'This Windows account already belongs to a different AUCC server. Uninstall the old Agent before moving this station.';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  Code: Integer;
begin
  if CurStep = ssPostInstall then
    if not Exec(ExpandConstant('{sys}\certutil.exe'),
      '-user -addstore Root "' + ExpandConstant('{app}\server-ca.pem') + '"',
      '', SW_HIDE, ewWaitUntilTerminated, Code) or (Code <> 0) then
      RaiseException('Could not trust the AUCC certificate for this Windows account.');
end;
#endif
